// <auto-generated />
using DataRepositories.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataRepositories.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240302085558_AddArticle")]
    partial class AddArticle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("StockKeepingUnit")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Excavator",
                            Price = 449.99m,
                            StockKeepingUnit = "LEGO-42100"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lamborghini Sián",
                            Price = 399.99m,
                            StockKeepingUnit = "LEGO-42115"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Millennium Falcon",
                            Price = 849.99m,
                            StockKeepingUnit = "LEGO-75192"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Verkenningsrover op Mars",
                            Price = 149.99m,
                            StockKeepingUnit = "LEGO-42180"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Concorde",
                            Price = 119.99m,
                            StockKeepingUnit = "LEGO-10318"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Treinrails",
                            Price = 19.99m,
                            StockKeepingUnit = "LEGO-60205"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Wissels",
                            Price = 19.99m,
                            StockKeepingUnit = "LEGO-60238"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Passagierssneltrein",
                            Price = 159.99m,
                            StockKeepingUnit = "LEGO-60337"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Titanic",
                            Price = 679.99m,
                            StockKeepingUnit = "LEGO-10294"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lego Minifiguren serie",
                            Price = 3.99m,
                            StockKeepingUnit = "LEGO-71045"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
